<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

do_action( 'genesis_doctype' );
do_action( 'genesis_title' );
do_action( 'genesis_meta' );

wp_head(); //* we need this for plugins
?>
</head>
<?php

$GTM = '
		<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-NVHXBB"
		 height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
		 <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':
		 new Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],
		 j=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=
		 \'//www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);
		 })(window,document,\'script\',\'dataLayer\',\'GTM-NVHXBB\');</script>
		<!-- End Google Tag Manager -->
	';

genesis_markup( array(
	'html5'   => '<body %s id="geneid"> '.$GTM,
	'xhtml'   => sprintf( '<body class="%s" id="geneid2">', implode( ' ', get_body_class() ) ),
	'context' => 'body',
) );


do_action( 'genesis_before' );

add_action( 'genesis_before', 'add_GTM_code' );
function add_GTM_code () {
	if ( current_filter() == 'genesis_before' ) {
		echo '<div class="gene">hello gene</div>';
	}
}

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="wrap">',
	'context' => 'site-container',
) );

do_action( 'genesis_before_header' );
do_action( 'genesis_header' );
do_action( 'genesis_after_header' );

genesis_markup( array(
	'html5'   => '<div %s>',
	'xhtml'   => '<div id="inner">',
	'context' => 'site-inner',
) );
genesis_structural_wrap( 'site-inner' );
